In [9]:
# Data Visualization
# BTech Computer Science Stream , January 2025
# Week 3 NumPy Basics: Arrays and Vectorized Computation - Demonstration Code
# Name: Divyansh Garg , reg number - 240953118 , Date: 27/01/2025

In [12]:
import numpy as np

In [21]:
import random
n=np.random.randint(1,51,size=(3,4))
print(n)
n_mean=np.mean(n)
n_median=np.median(n)
n_std=np.std(n)
print("Mean =",n_mean,"\n","Median =",n_median,"\n","Standard dev =",n_std)
sum1= np.sum(n)
sum2=np.sum(n,axis=1)
print("Sum of matrix is: ",sum1,"\n","Sum of each row element is: ",sum2)
new_matrix=np.reshape(n,(2,6))
print("New matrix now is: ")
new_matrix

[[ 4 17 46 36]
 [ 3  4  4 39]
 [29  9 34 37]]
Mean = 21.833333333333332 
 Median = 23.0 
 Standard dev = 15.826314233649674
Sum of matrix is:  262 
 Sum of each row element is:  [103  50 109]
New matrix now is: 


array([[ 4, 17, 46, 36,  3,  4],
       [ 4, 39, 29,  9, 34, 37]])

In [37]:
a=np.random.randint(1,100,size=(3,3))
b=np.random.randint(1,50,size=(3,3))
print("Matrix 1 is: \n")
print(a,"\n")
print("Matrix 2 is: \n")
print(b,"\n")
print("Sum of 2 matrix is :")
add = a+b
print(add)
print("Difference of 2 matrix is: ")
diff=a-b
print(diff)
print("Prouct of each element of the 2 matrix is: ")
prod=a*b
print(prod)
print("Dot product: ")
dotprod=a.dot(b)
print(dotprod)
transpose_A = a.T
transpose_B = b.T
print("\nTranspose of Matrix A:")
print(transpose_A)
print("\nTranspose of Matrix B:")
print(transpose_B)
det_A = np.linalg.det(a)
det_B = np.linalg.det(b)
print("\nDeterminant of A:", det_A)
print("Determinant of B:", det_B)
if det_A != 0:
    inverse_A = np.linalg.inv(a)
    print("\nInverse of Matrix A:")
    print(inverse_A)
else:
    print("\nMatrix A is singular and doesn't have an inverse.")
if det_B != 0:
    inverse_B = np.linalg.inv(b)
    print("\nInverse of Matrix B:")
    print(inverse_B)
else:
    print("\nMatrix B is singular and doesn't have an inverse.")

Matrix 1 is: 

[[16  2 37]
 [89 92 69]
 [93 61 25]] 

Matrix 2 is: 

[[43 31 35]
 [ 5 22 16]
 [42 33  6]] 

Sum of 2 matrix is :
[[ 59  33  72]
 [ 94 114  85]
 [135  94  31]]
Difference of 2 matrix is: 
[[-27 -29   2]
 [ 84  70  53]
 [ 51  28  19]]
Prouct of each element of the 2 matrix is: 
[[ 688   62 1295]
 [ 445 2024 1104]
 [3906 2013  150]]
Dot product: 
[[2252 1761  814]
 [7185 7060 5001]
 [5354 5050 4381]]

Transpose of Matrix A:
[[16 89 93]
 [ 2 92 61]
 [37 69 25]]

Transpose of Matrix B:
[[43  5 42]
 [31 22 33]
 [35 16  6]]

Determinant of A: -137858.99999999985
Determinant of B: -23691.000000000022

Inverse of Matrix A:
[[ 0.01384748 -0.01600911  0.02369087]
 [-0.03040788  0.02205877 -0.01587854]
 [ 0.0226826   0.00573049 -0.0093864 ]]

Inverse of Matrix B:
[[ 0.01671521 -0.04090161  0.01156557]
 [-0.0270989   0.05115867  0.02165379]
 [ 0.03203748  0.00493858 -0.03338821]]
